server:
    port: 5001

news_api_key: 6c31ae36c2bb4baa8826528f90676ba7

spring:
    datasource:
        url: jdbc:mysql://newsgen.cu7vgahbddep.us-west-2.rds.amazonaws.com/newsgen
        username: DHua5922
        password: blackhand12345
    jpa:
        hibernate:
            ddl-auto: update