name: Deploy To Staging Environment on Heroku

on:
  push:
    branches:
      - CU-r76jfc_Revamp-registration-UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_STAGE_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true