name: Deploy Front End Stage To Heroku

on:
  push:
    branches:
      - CU-wkfhxf_Convert-to-monorepo
    paths:
      - frontend/**
      - .github/workflows/stage-frontend.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_STAGE_FRONTEND}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: ${{secrets.FRONTEND_DIRECTORY}}